export { default as BackspaceIcon } from './backspace.svg?react'
export { default as EnterIcon } from './enter.svg?react'
export { default as MoonStarsIcon } from './moonstars.svg?react'
export { default as SunIcon } from './sun.svg?react'
export { default as WordleIcon } from './wordle-icon.svg?react'
